### PR TITLE
Implement home screen

### PR DESCRIPTION
**Pull request by ChaoticWeg**
Creating this PR to serve as a point of discussion and review while I work on implementing the home screen. Input is encouraged!

Will request CR once I feel the work is complete.

### CODE REVIEW

**Comment by ChaoticWeg** [comment]
[Implement home screen layout](https://trello.com/c/UY9Vl4eE/27-implement-home-screen-layout)

**Comment by ChaoticWeg** [comment]
image

Travis fails to validate snapshots because they're on UTC and we're on UTC-6. Need to figure out a way to avoid this issue. Maybe we can force Travis to mock a timezone? Or set the timezone in a script that runs before `yarn test:ci`?

cc @richardkriesman

**Comment by ChaoticWeg** [comment]
Fixed. Added to `travis.yml`:

```
...
before_script:
  - export TZ=America/Chicago
...
```

**Review by richardkriesman — CHANGES_REQUESTED** [review]
Tested this on my device and it seems to work well! Only change I'd suggest is to add `private` and `public` keywords as appropriate for some of the component classes, since that's natively supported in TS.

**Review by richardkriesman — APPROVED** [review]

**Comment by richardkriesman** [comment]
@ChaoticWeg I added the aforementioned changes and went ahead and approved it. I can't add you as a reviewer since you're the author, so go ahead and give it a look over and you can do the honors of merging if it seems good to you.

**Comment by ChaoticWeg** [comment]
Will do when I get home!

**Comment by ChaoticWeg** [comment]
Looks good to me. Merging!

**Pull request merged**
