### PR TITLE
Implement Settings screen UI prototype

### LINKED ISSUE #14: Settings screen
Going to work on applying a stack navigator and using it to open the Settings screen when the "switch" button is tapped. Will link PR shortly.

### PR DESCRIPTION
**Pull request by ChaoticWeg**
This PR will resolve #14 once complete. I am working now on applying a stack navigator to the app and popping the settings screen on top of the main screen when the appropriate events fire.

Marginally related: @richardkriesman can we get repo projects for each of the screens? Would like to be able to attach this PR to a "Settings screen" project, #13 to a "Home screen" project, &c.

### CODE REVIEW

**Comment by ChaoticWeg** [comment]
Received some code from @miika22 that helped greatly with creating the navigation flow!

I have made one executive change: everything will be in a _single_ StackNavigator. I realized that it's possible to hide the header on a screen, so the Home screen will just be the root of the navigator. Everything is working ok now, and I'm working on making it look more like the mockups before pushing.

**Comment by ChaoticWeg** [comment]
@richardkriesman Can I get your help with configuring jest to handle testing the navigation? Whenever you get the chance. ETA for this PR is tomorrow night.

**Comment by ChaoticWeg** [comment]
Looks like all that's left to do is update jest to handle screens other than Home, and add the buttons in the header. I'm headed off for maybe the rest of the day, so if anyone else wants to take a crack at it, go for it.

**Comment by ChaoticWeg** [comment]
Going to work on the settings screen some more.

**Comment by ChaoticWeg** [comment]
Requesting a merge to get the navigation stuff into `develop`. Will not close the PR or delete the branch.

**Review by richardkriesman — APPROVED** [review]

**Comment by ChaoticWeg** [comment]
Keeping this PR open. Do not delete the branch.

**Comment by ChaoticWeg** [comment]
Hmm. Okay, it looks like the basics are done. Closing this PR because for whatever reason GitHub forgot about this PR after that merge.

**Pull request merged**
